(() => {
  const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d');
  const overlay=document.querySelector('#overlay'),overlayKicker=document.querySelector('#overlay-kicker'),overlayTitle=document.querySelector('#overlay-title'),overlayCopy=document.querySelector('#overlay-copy'),overlayScore=document.querySelector('#overlay-score'),overlayAction=document.querySelector('#overlay-action');
  const scoreEl=document.querySelector('#live-score'),nameEl=document.querySelector('#game-name'),hintEl=document.querySelector('#hint'),pauseButton=document.querySelector('#pause'),muteButton=document.querySelector('#mute'),announcer=document.querySelector('#announcer'),cards=[...document.querySelectorAll('.card')];
  const W=canvas.width,H=canvas.height,p={bg:'#050609',purple:'#9b5cff',lime:'#b9ff38',pink:'#ff3fd8',text:'#f6f2ff',muted:'#80778f',danger:'#ff496c'};
  const config={runner:{name:'NEON RUNNER',title:'네온 러너',kicker:'GAME 01 / EASY',copy:'스페이스바 또는 화면을 눌러 장애물을 뛰어넘으세요.',hint:'SPACE / TAP — 점프'},memory:{name:'GLITCH MEMORY',title:'글리치 메모리',kicker:'GAME 02 / NORMAL',copy:'45초 안에 같은 네온 심볼 여섯 쌍을 모두 찾으세요.',hint:'CLICK / TAP — 카드 뒤집기'},reaction:{name:'BLOCK CATCHER',title:'블록 캐처',kicker:'GAME 03 / HARD',copy:'블록이 바닥에 닿기 전에 클릭하세요. 다섯 개를 놓치면 종료됩니다.',hint:'CLICK / TAP — 블록 잡기'}};
  let game='runner',status='ready',score=0,raf=0,last=0,muted=false,audio=null,s={};
  const bestKey=id=>`dolldom-best-${id}`,getBest=id=>Number(localStorage.getItem(bestKey(id))||0);
  const refreshBests=()=>document.querySelectorAll('[data-best]').forEach(el=>el.textContent=`BEST ${String(getBest(el.dataset.best)).padStart(4,'0')}`);
  const setBest=(id,value)=>{const best=Math.max(getBest(id),Math.floor(value));localStorage.setItem(bestKey(id),String(best));refreshBests();return best};
  const tone=(freq=440,duration=.07,type='square')=>{if(muted)return;try{audio||=new(window.AudioContext||window.webkitAudioContext)();const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(.045,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+duration)}catch{}};
  function backdrop(){ctx.fillStyle=p.bg;ctx.fillRect(0,0,W,H);ctx.strokeStyle='#231a32';ctx.lineWidth=1;for(let x=0;x<W;x+=40){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke()}for(let y=0;y<H;y+=40){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}const g=ctx.createRadialGradient(W*.78,H*.2,0,W*.78,H*.2,160);g.addColorStop(0,'#7428a955');g.addColorStop(1,'#7428a900');ctx.fillStyle=g;ctx.fillRect(0,0,W,H)}
  function roundRect(x,y,w,h,r,fill,stroke){ctx.beginPath();ctx.roundRect(x,y,w,h,r);if(fill){ctx.fillStyle=fill;ctx.fill()}if(stroke){ctx.strokeStyle=stroke;ctx.stroke()}}
  function setupRunner(){s={player:{x:94,y:270,vy:0,w:42,h:42},obstacles:[],spawn:0,speed:285,distance:0}}
  function runnerJump(){const q=s.player;if(q&&q.y>=269){q.vy=-620;tone(520,.08)}}
  function updateRunner(dt){const q=s.player;q.vy+=1500*dt;q.y=Math.min(270,q.y+q.vy*dt);s.spawn-=dt;s.distance+=s.speed*dt;if(s.spawn<=0){const h=34+Math.random()*40;s.obstacles.push({x:W+20,y:312-h,w:20+Math.random()*18,h});s.spawn=.85+Math.random()*.75;s.speed=Math.min(470,s.speed+3)}s.obstacles.forEach(o=>o.x-=s.speed*dt);s.obstacles=s.obstacles.filter(o=>o.x>-60);score=Math.floor(s.distance/18);for(const o of s.obstacles){if(q.x+7<o.x+o.w&&q.x+q.w-7>o.x&&q.y+6<o.y+o.h&&q.y+q.h>o.y)endGame('신호 충돌!')}}
  function drawRunner(){backdrop();ctx.fillStyle='#492766';ctx.beginPath();ctx.arc(W*.8,95,62,0,Math.PI*2);ctx.fill();ctx.fillStyle=p.pink;ctx.globalAlpha=.5;ctx.beginPath();ctx.arc(W*.8,95,54,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;ctx.strokeStyle=p.lime;ctx.lineWidth=3;ctx.shadowColor=p.lime;ctx.shadowBlur=14;ctx.beginPath();ctx.moveTo(0,312);ctx.lineTo(W,312);ctx.stroke();ctx.shadowBlur=0;for(let i=0;i<15;i++){const x=(i*72-s.distance*.35)%W;ctx.strokeStyle='#18362b';ctx.beginPath();ctx.moveTo(x,312);ctx.lineTo(x-70,H);ctx.stroke()}const q=s.player;ctx.save();ctx.translate(q.x+q.w/2,q.y+q.h/2);ctx.fillStyle=p.lime;ctx.shadowColor=p.lime;ctx.shadowBlur=15;ctx.beginPath();ctx.ellipse(0,0,22,14,0,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.moveTo(-18,0);ctx.lineTo(-37,-18);ctx.lineTo(-34,17);ctx.closePath();ctx.fill();ctx.fillStyle=p.bg;ctx.beginPath();ctx.arc(10,-3,3,0,Math.PI*2);ctx.fill();ctx.restore();s.obstacles.forEach(o=>{ctx.fillStyle=p.pink;ctx.shadowColor=p.pink;ctx.shadowBlur=12;ctx.fillRect(o.x,o.y,o.w,o.h);ctx.shadowBlur=0;ctx.fillStyle='#ffffff77';ctx.fillRect(o.x+4,o.y+5,3,o.h-10)})}
  function setupMemory(){const symbols=['◆','●','▲','✦','⬟','≋'];s={deck:[...symbols,...symbols].sort(()=>Math.random()-.5).map(symbol=>({symbol,open:false,matched:false})),first:null,lock:false,time:45,matches:0}}
  function updateMemory(dt){s.time-=dt;score=Math.max(0,Math.round(s.matches*220+s.time*10));if(s.time<=0)endGame('시간 초과!')}
  function memoryPick(px,py){if(status!=='playing'||s.lock)return;const gap=14,cw=142,ch=80,startX=55,startY=28,col=Math.floor((px-startX)/(cw+gap)),row=Math.floor((py-startY)/(ch+gap));if(col<0||col>3||row<0||row>2)return;const i=row*4+col,card=s.deck[i];if(!card||card.open||card.matched)return;card.open=true;tone(360+i*18,.06);if(s.first===null){s.first=i;return}const first=s.deck[s.first];if(first.symbol===card.symbol){first.matched=card.matched=true;s.matches++;s.first=null;tone(720,.12,'sine');if(s.matches===6){score=Math.round(1500+s.time*30);setTimeout(()=>endGame('모든 기억 복구!'),250)}}else{s.lock=true;setTimeout(()=>{first.open=false;card.open=false;s.first=null;s.lock=false},650)}}
  function drawMemory(){backdrop();const gap=14,cw=142,ch=80,startX=55,startY=28;s.deck.forEach((c,i)=>{const col=i%4,row=Math.floor(i/4),x=startX+col*(cw+gap),y=startY+row*(ch+gap);roundRect(x,y,cw,ch,10,c.matched?'#233d24':c.open?'#2b1749':'#0f0b18',c.matched?p.lime:'#4b3869');if(c.open||c.matched){ctx.fillStyle=c.matched?p.lime:p.pink;ctx.font='700 34px sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.shadowColor=ctx.fillStyle;ctx.shadowBlur=12;ctx.fillText(c.symbol,x+cw/2,y+ch/2);ctx.shadowBlur=0}else{ctx.fillStyle='#392a50';ctx.font='700 24px sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('?',x+cw/2,y+ch/2)}});ctx.textAlign='left';ctx.fillStyle=s.time<10?p.danger:p.lime;ctx.font='700 14px monospace';ctx.fillText(`TIME ${Math.max(0,s.time).toFixed(1)}s`,55,348)}
  function setupReaction(){s={blocks:[],spawn:0,lives:5,speed:115,time:0,hits:0}}
  function updateReaction(dt){s.spawn-=dt;s.time+=dt;s.speed=Math.min(260,115+s.time*5);if(s.spawn<=0){const size=34+Math.random()*24;s.blocks.push({x:30+Math.random()*(W-60-size),y:-size,size,color:Math.random()>.5?p.pink:p.purple,phase:Math.random()*6});s.spawn=Math.max(.25,.7-s.time*.012)}for(const b of s.blocks)b.y+=s.speed*dt;const missed=s.blocks.filter(b=>b.y>H+10).length;if(missed){s.lives-=missed;tone(130,.12,'sawtooth');s.blocks=s.blocks.filter(b=>b.y<=H+10);if(s.lives<=0)endGame('신호를 놓쳤어요!')}score=Math.floor(s.time*8)+s.hits*100}
  function reactionPick(px,py){if(status!=='playing')return;for(let i=s.blocks.length-1;i>=0;i--){const b=s.blocks[i];if(px>=b.x-8&&px<=b.x+b.size+8&&py>=b.y-8&&py<=b.y+b.size+8){s.blocks.splice(i,1);s.hits++;score=Math.floor(s.time*8)+s.hits*100;tone(640+s.hits*12,.05);return}}tone(180,.03)}
  function drawReaction(){backdrop();ctx.fillStyle=p.muted;ctx.font='700 13px monospace';ctx.fillText(`SHIELDS ${'◆'.repeat(Math.max(0,s.lives))}`,28,30);for(const b of s.blocks){ctx.save();ctx.translate(b.x+b.size/2,b.y+b.size/2);ctx.rotate(s.time*.7+b.phase);ctx.fillStyle=b.color;ctx.shadowColor=b.color;ctx.shadowBlur=18;ctx.fillRect(-b.size/2,-b.size/2,b.size,b.size);ctx.fillStyle='#ffffff66';ctx.fillRect(-b.size/2+6,-b.size/2+6,5,b.size-12);ctx.restore()}ctx.strokeStyle=p.danger;ctx.setLineDash([8,8]);ctx.beginPath();ctx.moveTo(0,H-18);ctx.lineTo(W,H-18);ctx.stroke();ctx.setLineDash([])}
  function init(){cancelAnimationFrame(raf);score=0;last=0;if(game==='runner')setupRunner();if(game==='memory')setupMemory();if(game==='reaction')setupReaction();draw();updateHud()}
  function start(){if(status==='playing')return;if(status==='paused'){status='playing';last=0;overlay.classList.add('hidden');pauseButton.textContent='Ⅱ';raf=requestAnimationFrame(loop);announce('게임 계속');return}init();status='playing';overlay.classList.add('hidden');tone(420,.09);raf=requestAnimationFrame(loop);announce(`${config[game].title} 시작`)}
  function pause(){if(status==='playing'){status='paused';cancelAnimationFrame(raf);showOverlay('PAUSED','잠시 멈춤','준비되면 계속하세요.','계속하기');pauseButton.textContent='▶';announce('게임 일시정지')}else if(status==='paused')start()}
  function restart(){status='ready';init();showReady();tone(280,.05)}
  function endGame(message){if(status==='gameover')return;status='gameover';cancelAnimationFrame(raf);const best=setBest(game,score);overlayKicker.textContent=`GAME OVER / BEST ${String(best).padStart(4,'0')}`;overlayTitle.textContent=message;overlayCopy.textContent='이번 점수를 저장했어요. 한 번 더 도전해볼까요?';overlayScore.hidden=false;overlayScore.textContent=Math.floor(score);overlayAction.textContent='다시 플레이';overlay.classList.remove('hidden');tone(110,.25,'sawtooth');announce(`게임 종료, 점수 ${Math.floor(score)}`)}
  function showReady(){const c=config[game];overlayKicker.textContent=c.kicker;overlayTitle.textContent=c.title;overlayCopy.textContent=c.copy;overlayScore.hidden=true;overlayAction.textContent='게임 시작';overlay.classList.remove('hidden');pauseButton.textContent='Ⅱ'}
  function showOverlay(kicker,title,copy,action){overlayKicker.textContent=kicker;overlayTitle.textContent=title;overlayCopy.textContent=copy;overlayScore.hidden=true;overlayAction.textContent=action;overlay.classList.remove('hidden')}
  function selectGame(id){if(!config[id])return;game=id;status='ready';cards.forEach(card=>card.classList.toggle('active',card.dataset.game===id));nameEl.textContent=config[id].name;hintEl.textContent=config[id].hint;init();showReady();document.querySelector('#console').scrollIntoView({behavior:'smooth',block:'center'});announce(`${config[id].title} 선택`)}
  function updateHud(){scoreEl.textContent=`SCORE ${String(Math.floor(score)).padStart(4,'0')}`}
  function draw(){if(game==='runner')drawRunner();if(game==='memory')drawMemory();if(game==='reaction')drawReaction();updateHud()}
  function loop(now){if(status!=='playing')return;const dt=Math.min(.033,(now-last)/1000||0);last=now;if(game==='runner')updateRunner(dt);if(game==='memory')updateMemory(dt);if(game==='reaction')updateReaction(dt);draw();if(status==='playing')raf=requestAnimationFrame(loop)}
  function point(evt){const rect=canvas.getBoundingClientRect();return{x:(evt.clientX-rect.left)*W/rect.width,y:(evt.clientY-rect.top)*H/rect.height}}
  function interact(evt){evt.preventDefault();if(status==='ready'||status==='gameover'){start();return}if(status!=='playing')return;const q=point(evt);if(game==='runner')runnerJump();if(game==='memory')memoryPick(q.x,q.y);if(game==='reaction')reactionPick(q.x,q.y)}
  function announce(text){announcer.textContent=text}
  canvas.addEventListener('pointerdown',interact);cards.forEach(card=>card.addEventListener('click',()=>selectGame(card.dataset.game)));overlayAction.addEventListener('click',start);pauseButton.addEventListener('click',pause);document.querySelector('#restart').addEventListener('click',restart);
  muteButton.addEventListener('click',()=>{muted=!muted;muteButton.textContent=muted?'×':'♪';muteButton.setAttribute('aria-label',muted?'소리 켜기':'음소거');announce(muted?'소리 꺼짐':'소리 켜짐')});document.querySelector('#play-now').addEventListener('click',()=>setTimeout(()=>{if(status==='ready')start()},450));
  window.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA'].includes(document.activeElement.tagName))return;if(e.code==='Space'){e.preventDefault();if(status==='ready'||status==='gameover')start();else if(game==='runner'&&status==='playing')runnerJump()}if(e.key.toLowerCase()==='p')pause();if(e.key.toLowerCase()==='r')restart();if(['1','2','3'].includes(e.key))selectGame(['runner','memory','reaction'][Number(e.key)-1])});document.addEventListener('visibilitychange',()=>{if(document.hidden&&status==='playing')pause()});
  refreshBests();init();showReady();
})();
